# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(767, 557)
        MainWindow.setMinimumSize(QtCore.QSize(295, 218))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.optionsHolder = QtWidgets.QScrollArea(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.optionsHolder.sizePolicy().hasHeightForWidth())
        self.optionsHolder.setSizePolicy(sizePolicy)
        self.optionsHolder.setMinimumSize(QtCore.QSize(150, 0))
        self.optionsHolder.setMaximumSize(QtCore.QSize(200, 16777215))
        self.optionsHolder.setWidgetResizable(True)
        self.optionsHolder.setObjectName("optionsHolder")
        self.optionsHolderContents = QtWidgets.QWidget()
        self.optionsHolderContents.setGeometry(QtCore.QRect(0, 0, 198, 492))
        self.optionsHolderContents.setObjectName("optionsHolderContents")
        self.optionsVerticalLayout = QtWidgets.QVBoxLayout(self.optionsHolderContents)
        self.optionsVerticalLayout.setContentsMargins(2, 2, 2, 2)
        self.optionsVerticalLayout.setSpacing(5)
        self.optionsVerticalLayout.setObjectName("optionsVerticalLayout")
        self.instrumentName = QtWidgets.QLabel(self.optionsHolderContents)
        self.instrumentName.setAlignment(QtCore.Qt.AlignCenter)
        self.instrumentName.setObjectName("instrumentName")
        self.optionsVerticalLayout.addWidget(self.instrumentName)
        self.colorChanger = QtWidgets.QWidget(self.optionsHolderContents)
        self.colorChanger.setMinimumSize(QtCore.QSize(80, 70))
        self.colorChanger.setMaximumSize(QtCore.QSize(80, 70))
        self.colorChanger.setObjectName("colorChanger")
        self.backgroundColorChange = ClickableGraphicsView(self.colorChanger)
        self.backgroundColorChange.setGeometry(QtCore.QRect(20, 20, 40, 40))
        self.backgroundColorChange.setObjectName("backgroundColorChange")
        self.foregroundColorChange = ClickableGraphicsView(self.colorChanger)
        self.foregroundColorChange.setGeometry(QtCore.QRect(0, 0, 40, 40))
        self.foregroundColorChange.setObjectName("foregroundColorChange")
        self.swapColors = QtWidgets.QPushButton(self.colorChanger)
        self.swapColors.setGeometry(QtCore.QRect(40, 0, 21, 21))
        self.swapColors.setFlat(True)
        self.swapColors.setObjectName("swapColors")
        self.optionsVerticalLayout.addWidget(self.colorChanger)
        self.brushSizeChanger = QtWidgets.QWidget(self.optionsHolderContents)
        self.brushSizeChanger.setObjectName("brushSizeChanger")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.brushSizeChanger)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(8)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.brushSizeChanger)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.brushSize = QtWidgets.QSpinBox(self.brushSizeChanger)
        self.brushSize.setMaximum(10000)
        self.brushSize.setProperty("value", 5)
        self.brushSize.setObjectName("brushSize")
        self.horizontalLayout_2.addWidget(self.brushSize)
        spacerItem = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.optionsVerticalLayout.addWidget(self.brushSizeChanger)
        self.figureChanger = QtWidgets.QWidget(self.optionsHolderContents)
        self.figureChanger.setObjectName("figureChanger")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.figureChanger)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(8)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.figureChanger)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.figure = QtWidgets.QComboBox(self.figureChanger)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.figure.sizePolicy().hasHeightForWidth())
        self.figure.setSizePolicy(sizePolicy)
        self.figure.setObjectName("figure")
        self.horizontalLayout_3.addWidget(self.figure)
        spacerItem1 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.optionsVerticalLayout.addWidget(self.figureChanger)
        self.figureFillChanger = QtWidgets.QWidget(self.optionsHolderContents)
        self.figureFillChanger.setObjectName("figureFillChanger")
        self.figureFillChangerLayout = QtWidgets.QVBoxLayout(self.figureFillChanger)
        self.figureFillChangerLayout.setSpacing(3)
        self.figureFillChangerLayout.setObjectName("figureFillChangerLayout")
        self.label_3 = QtWidgets.QLabel(self.figureFillChanger)
        self.label_3.setObjectName("label_3")
        self.figureFillChangerLayout.addWidget(self.label_3)
        self.noFill = QtWidgets.QRadioButton(self.figureFillChanger)
        self.noFill.setObjectName("noFill")
        self.figureFillChangerGroup = QtWidgets.QButtonGroup(MainWindow)
        self.figureFillChangerGroup.setObjectName("figureFillChangerGroup")
        self.figureFillChangerGroup.addButton(self.noFill)
        self.figureFillChangerLayout.addWidget(self.noFill)
        self.frontFill = QtWidgets.QRadioButton(self.figureFillChanger)
        self.frontFill.setObjectName("frontFill")
        self.figureFillChangerGroup.addButton(self.frontFill)
        self.figureFillChangerLayout.addWidget(self.frontFill)
        self.backFill = QtWidgets.QRadioButton(self.figureFillChanger)
        self.backFill.setObjectName("backFill")
        self.figureFillChangerGroup.addButton(self.backFill)
        self.figureFillChangerLayout.addWidget(self.backFill)
        self.optionsVerticalLayout.addWidget(self.figureFillChanger)
        spacerItem2 = QtWidgets.QSpacerItem(20, 339, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.optionsVerticalLayout.addItem(spacerItem2)
        self.optionsHolder.setWidget(self.optionsHolderContents)
        self.imHolder = QtWidgets.QScrollArea(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imHolder.sizePolicy().hasHeightForWidth())
        self.imHolder.setSizePolicy(sizePolicy)
        self.imHolder.setWidgetResizable(True)
        self.imHolder.setObjectName("imHolder")
        self.imHolderContents = QtWidgets.QWidget()
        self.imHolderContents.setGeometry(QtCore.QRect(0, 0, 559, 492))
        self.imHolderContents.setObjectName("imHolderContents")
        self.pictureHolder = QtWidgets.QGridLayout(self.imHolderContents)
        self.pictureHolder.setObjectName("pictureHolder")
        self.field = Field(self.imHolderContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.field.sizePolicy().hasHeightForWidth())
        self.field.setSizePolicy(sizePolicy)
        self.field.setText("")
        self.field.setAlignment(QtCore.Qt.AlignCenter)
        self.field.setObjectName("field")
        self.pictureHolder.addWidget(self.field, 0, 1, 1, 1)
        self.imHolder.setWidget(self.imHolderContents)
        self.horizontalLayout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 767, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.instrumentsBar = QtWidgets.QToolBar(MainWindow)
        self.instrumentsBar.setMovable(False)
        self.instrumentsBar.setObjectName("instrumentsBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.instrumentsBar)
        self.action_new = QtWidgets.QAction(MainWindow)
        self.action_new.setObjectName("action_new")
        self.action_open = QtWidgets.QAction(MainWindow)
        self.action_open.setObjectName("action_open")
        self.action_save = QtWidgets.QAction(MainWindow)
        self.action_save.setObjectName("action_save")
        self.menu.addAction(self.action_new)
        self.menu.addAction(self.action_open)
        self.menu.addAction(self.action_save)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Aint"))
        self.instrumentName.setText(_translate("MainWindow", "Имя инструмента"))
        self.swapColors.setText(_translate("MainWindow", "↔"))
        self.label.setText(_translate("MainWindow", "Толщина"))
        self.label_2.setText(_translate("MainWindow", "Фигура"))
        self.label_3.setText(_translate("MainWindow", "Цвет заливки"))
        self.noFill.setText(_translate("MainWindow", "Без заливки"))
        self.frontFill.setText(_translate("MainWindow", "Передний план"))
        self.backFill.setText(_translate("MainWindow", "Задний план"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.instrumentsBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.action_new.setText(_translate("MainWindow", "Новый"))
        self.action_new.setToolTip(_translate("MainWindow", "Новый"))
        self.action_new.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.action_open.setText(_translate("MainWindow", "Открыть"))
        self.action_open.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.action_save.setText(_translate("MainWindow", "Сохранить"))
        self.action_save.setShortcut(_translate("MainWindow", "Ctrl+S"))

from src.clickableGraphicsView import ClickableGraphicsView
from src.field import Field
