# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(767, 557)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(2, 2, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.imHolder = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imHolder.sizePolicy().hasHeightForWidth())
        self.imHolder.setSizePolicy(sizePolicy)
        self.imHolder.setWidgetResizable(True)
        self.imHolder.setObjectName("imHolder")
        self.imHolderContents = QtWidgets.QWidget()
        self.imHolderContents.setGeometry(QtCore.QRect(0, 0, 592, 492))
        self.imHolderContents.setObjectName("imHolderContents")
        self.pictureHolder = QtWidgets.QGridLayout(self.imHolderContents)
        self.pictureHolder.setObjectName("pictureHolder")
        self.imHolder.setWidget(self.imHolderContents)
        self.gridLayout_2.addWidget(self.imHolder, 0, 1, 1, 1)
        self.optionsHolder = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.optionsHolder.sizePolicy().hasHeightForWidth())
        self.optionsHolder.setSizePolicy(sizePolicy)
        self.optionsHolder.setWidgetResizable(True)
        self.optionsHolder.setObjectName("optionsHolder")
        self.optionsHolderContents = QtWidgets.QWidget()
        self.optionsHolderContents.setGeometry(QtCore.QRect(0, 0, 169, 492))
        self.optionsHolderContents.setObjectName("optionsHolderContents")
        self.optionsVerticalLayout = QtWidgets.QVBoxLayout(self.optionsHolderContents)
        self.optionsVerticalLayout.setContentsMargins(2, 2, 2, 2)
        self.optionsVerticalLayout.setSpacing(5)
        self.optionsVerticalLayout.setObjectName("optionsVerticalLayout")
        self.instrumentName = QtWidgets.QLabel(self.optionsHolderContents)
        self.instrumentName.setAlignment(QtCore.Qt.AlignCenter)
        self.instrumentName.setObjectName("instrumentName")
        self.optionsVerticalLayout.addWidget(self.instrumentName)
        self.colorChange = QtWidgets.QWidget(self.optionsHolderContents)
        self.colorChange.setMinimumSize(QtCore.QSize(80, 70))
        self.colorChange.setMaximumSize(QtCore.QSize(80, 70))
        self.colorChange.setObjectName("colorChange")
        self.backgroundColor = QtWidgets.QGraphicsView(self.colorChange)
        self.backgroundColor.setGeometry(QtCore.QRect(20, 20, 41, 41))
        self.backgroundColor.setObjectName("backgroundColor")
        self.foregroundColor = QtWidgets.QGraphicsView(self.colorChange)
        self.foregroundColor.setGeometry(QtCore.QRect(0, 0, 41, 41))
        self.foregroundColor.setObjectName("foregroundColor")
        self.swapColors = QtWidgets.QPushButton(self.colorChange)
        self.swapColors.setGeometry(QtCore.QRect(40, 0, 21, 21))
        self.swapColors.setFlat(True)
        self.swapColors.setObjectName("swapColors")
        self.optionsVerticalLayout.addWidget(self.colorChange)
        self.brushSizeChanger = QtWidgets.QWidget(self.optionsHolderContents)
        self.brushSizeChanger.setMinimumSize(QtCore.QSize(130, 40))
        self.brushSizeChanger.setMaximumSize(QtCore.QSize(150, 50))
        self.brushSizeChanger.setObjectName("brushSizeChanger")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.brushSizeChanger)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.brushSizeChanger)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.brushSize = QtWidgets.QSpinBox(self.brushSizeChanger)
        self.brushSize.setMaximum(10000)
        self.brushSize.setProperty("value", 5)
        self.brushSize.setObjectName("brushSize")
        self.horizontalLayout_2.addWidget(self.brushSize)
        self.optionsVerticalLayout.addWidget(self.brushSizeChanger)
        spacerItem = QtWidgets.QSpacerItem(20, 339, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.optionsVerticalLayout.addItem(spacerItem)
        self.optionsHolder.setWidget(self.optionsHolderContents)
        self.gridLayout_2.addWidget(self.optionsHolder, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 767, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.instrumentsBar = QtWidgets.QToolBar(MainWindow)
        self.instrumentsBar.setMovable(False)
        self.instrumentsBar.setObjectName("instrumentsBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.instrumentsBar)
        self.action_new = QtWidgets.QAction(MainWindow)
        self.action_new.setObjectName("action_new")
        self.action_open = QtWidgets.QAction(MainWindow)
        self.action_open.setObjectName("action_open")
        self.action_save = QtWidgets.QAction(MainWindow)
        self.action_save.setObjectName("action_save")
        self.menu.addAction(self.action_new)
        self.menu.addAction(self.action_open)
        self.menu.addAction(self.action_save)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Aint"))
        self.instrumentName.setText(_translate("MainWindow", "Имя инструмента"))
        self.swapColors.setText(_translate("MainWindow", "↔"))
        self.label.setText(_translate("MainWindow", "Размер"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.instrumentsBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.action_new.setText(_translate("MainWindow", "Новый"))
        self.action_new.setToolTip(_translate("MainWindow", "Новый"))
        self.action_new.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.action_open.setText(_translate("MainWindow", "Открыть"))
        self.action_open.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.action_save.setText(_translate("MainWindow", "Сохранить"))
        self.action_save.setShortcut(_translate("MainWindow", "Ctrl+S"))

